name: CI Test and PyInstaller Build

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest 

    strategy:
      matrix:
        python-version: ['3.13.7']
        
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 3. Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pyinstaller

      - name: 4. Run Tests
        run: |
          python -m unittest tests/test_model_handler.py